"use client"

import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export interface UserDataExport {
  userName: string
  email: string
  stats: {
    totalPhotos: number
    totalVideos: number
    totalJournals: number
    lastActive: Date
    streak: number
  }
  recentActivity: Array<{
    id: string
    type: 'photo' | 'video' | 'journal'
    title: string
    createdAt: Date
    thumbnail?: string
  }>
  exportDate: string
}

export interface JournalExportData {
  title: string
  author: string
  createdAt: Date
  mood?: string
  location?: string
  tags?: string[]
  content: string
  attachments?: Array<{
    type: "photo" | "video"
    url: string
    thumbnailUrl?: string
    fileId: string
    fileName: string
    size: number
  }>
}

export interface PhotoExportData {
  title: string
  description?: string
  url: string
  thumbnailUrl?: string
  album?: string
  tags?: string[]
  createdAt: Date
  fileName: string
  size: number
}

export interface VideoExportData {
  title: string
  description?: string
  url: string
  thumbnailUrl?: string
  category?: string
  tags?: string[]
  createdAt: Date
  fileName: string
  size: number
  duration?: number
}

export const exportUserDataToPDF = async (userData: UserDataExport): Promise<void> => {
  try {
    const pdf = new jsPDF()

    // Title page
    pdf.setFontSize(24)
    pdf.setTextColor(40, 40, 40)
    pdf.text('VidoraFrameForge Data Export', pdf.internal.pageSize.width / 2, 50, { align: 'center' })

    pdf.setFontSize(14)
    pdf.setTextColor(100, 100, 100)
    pdf.text(`Exported on ${new Date(userData.exportDate).toLocaleDateString()}`, pdf.internal.pageSize.width / 2, 70, { align: 'center' })

    // User info
    pdf.setFontSize(16)
    pdf.setTextColor(40, 40, 40)
    pdf.text('User Information', 20, 100)

    pdf.setFontSize(12)
    pdf.setTextColor(60, 60, 60)
    pdf.text(`Name: ${userData.userName}`, 20, 120)
    pdf.text(`Email: ${userData.email}`, 20, 135)
    pdf.text(`Last Active: ${new Date(userData.stats.lastActive).toLocaleDateString()}`, 20, 150)

    // Statistics
    pdf.setFontSize(16)
    pdf.setTextColor(40, 40, 40)
    pdf.text('Statistics', 20, 180)

    pdf.setFontSize(12)
    pdf.setTextColor(60, 60, 60)
    pdf.text(`Total Photos: ${userData.stats.totalPhotos}`, 20, 200)
    pdf.text(`Total Videos: ${userData.stats.totalVideos}`, 20, 215)
    pdf.text(`Total Journals: ${userData.stats.totalJournals}`, 20, 230)
    pdf.text(`Current Streak: ${userData.stats.streak} days`, 20, 245)

    // Recent Activity
    pdf.addPage()
    pdf.setFontSize(16)
    pdf.setTextColor(40, 40, 40)
    pdf.text('Recent Activity', 20, 30)

    pdf.setFontSize(11)
    pdf.setTextColor(60, 60, 60)

    let yPosition = 50
    userData.recentActivity.forEach((activity, index) => {
      if (yPosition > pdf.internal.pageSize.height - 30) {
        pdf.addPage()
        yPosition = 30
      }

      const activityType = activity.type.charAt(0).toUpperCase() + activity.type.slice(1)
      const date = activity.createdAt.toLocaleDateString()
      pdf.text(`${index + 1}. ${activityType}: ${activity.title}`, 20, yPosition)
      pdf.text(`   Date: ${date}`, 20, yPosition + 8)
      yPosition += 20
    })

    // Footer
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text(`Generated by VidoraFrameForge on ${new Date().toLocaleDateString()}`, 20, pdf.internal.pageSize.height - 10)
      pdf.text(`Page ${i} of ${pageCount}`, pdf.internal.pageSize.width - 30, pdf.internal.pageSize.height - 10)
    }

    const fileName = `vidoraframeforge_data_${userData.userName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${new Date().toISOString().split('T')[0]}.pdf`
    pdf.save(fileName)

  } catch (error) {
    console.error('Error generating user data PDF:', error)
    throw new Error('Failed to generate user data PDF')
  }
}

export const exportJournalToPDF = async (journalData: JournalExportData): Promise<void> => {
  try {
    // Create a new jsPDF instance
    const pdf = new jsPDF()

    // Set up fonts and colors
    pdf.setFont('helvetica', 'normal')

    // Add title
    pdf.setFontSize(20)
    pdf.setTextColor(40, 40, 40)
    const titleLines = pdf.splitTextToSize(journalData.title, 180)
    pdf.text(titleLines, 15, 25)

    let yPosition = 35 + (titleLines.length * 7)

    // Add metadata
    pdf.setFontSize(12)
    pdf.setTextColor(100, 100, 100)

    const metadata = [
      `Author: ${journalData.author}`,
      `Date: ${new Date(journalData.createdAt).toLocaleDateString()}`,
      ...(journalData.mood ? [`Mood: ${journalData.mood}`] : []),
      ...(journalData.location ? [`Location: ${journalData.location}`] : [])
    ]

    metadata.forEach(line => {
      pdf.text(line, 15, yPosition)
      yPosition += 7
    })

    yPosition += 5

    // Add tags if any
    if (journalData.tags && journalData.tags.length > 0) {
      pdf.setFontSize(11)
      pdf.setTextColor(60, 179, 113)
      const tagsText = `Tags: ${journalData.tags.map(tag => `#${tag}`).join(', ')}`
      const tagLines = pdf.splitTextToSize(tagsText, 180)
      pdf.text(tagLines, 15, yPosition)
      yPosition += (tagLines.length * 6) + 10
    }

    // Add content
    pdf.setFontSize(12)
    pdf.setTextColor(40, 40, 40)

    const contentLines = pdf.splitTextToSize(journalData.content, 180)
    const linesPerPage = Math.floor((pdf.internal.pageSize.height - yPosition - 20) / 6)

    let currentPage = 1
    let currentLine = 0

    while (currentLine < contentLines.length) {
      if (currentLine > 0) {
        pdf.addPage()
        yPosition = 20
        currentPage++
      }

      const endLine = Math.min(currentLine + linesPerPage, contentLines.length)
      const pageLines = contentLines.slice(currentLine, endLine)

      pdf.text(pageLines, 15, yPosition)
      currentLine = endLine
    }

    // Add attachments info if any
    if (journalData.attachments && journalData.attachments.length > 0) {
      pdf.addPage()
      pdf.setFontSize(16)
      pdf.setTextColor(40, 40, 40)
      pdf.text('Attachments', 15, 25)

      pdf.setFontSize(11)
      pdf.setTextColor(100, 100, 100)

      journalData.attachments.forEach((attachment, index) => {
        const yPos = 40 + (index * 15)
        if (yPos > pdf.internal.pageSize.height - 20) {
          pdf.addPage()
        }

        const fileName = attachment.fileName || `Attachment ${index + 1}`
        const fileType = attachment.type || 'Unknown'
        pdf.text(`${index + 1}. ${fileName} (${fileType})`, 15, yPos)
        pdf.text(`   URL: ${attachment.url}`, 15, yPos + 7)
      })
    }

    // Add footer with generation info
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text(`Generated by VidoraFrameForge on ${new Date().toLocaleDateString()}`, 15, pdf.internal.pageSize.height - 10)
      pdf.text(`Page ${i} of ${pageCount}`, pdf.internal.pageSize.width - 30, pdf.internal.pageSize.height - 10)
    }

    // Save the PDF
    const fileName = `${journalData.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_journal.pdf`
    pdf.save(fileName)

  } catch (error) {
    console.error('Error generating PDF:', error)
    throw new Error('Failed to generate PDF')
  }
}

export const exportMultipleJournalsToPDF = async (journals: JournalExportData[]): Promise<void> => {
  try {
    const pdf = new jsPDF()

    // Add title page
    pdf.setFontSize(24)
    pdf.setTextColor(40, 40, 40)
    pdf.text('Journal Collection', pdf.internal.pageSize.width / 2, 50, { align: 'center' })

    pdf.setFontSize(14)
    pdf.setTextColor(100, 100, 100)
    pdf.text(`Exported on ${new Date().toLocaleDateString()}`, pdf.internal.pageSize.width / 2, 70, { align: 'center' })
    pdf.text(`${journals.length} journal${journals.length !== 1 ? 's' : ''}`, pdf.internal.pageSize.width / 2, 85, { align: 'center' })

    let currentPage = 1

    // Add each journal
    for (const journal of journals) {
      pdf.addPage()
      currentPage++

      // Journal title
      pdf.setFontSize(18)
      pdf.setTextColor(40, 40, 40)
      const titleLines = pdf.splitTextToSize(journal.title, 180)
      pdf.text(titleLines, 15, 25)

      let yPosition = 35 + (titleLines.length * 7)

      // Metadata
      pdf.setFontSize(11)
      pdf.setTextColor(100, 100, 100)

      const metadata = [
        `Author: ${journal.author}`,
        `Date: ${new Date(journal.createdAt).toLocaleDateString()}`,
        ...(journal.mood ? [`Mood: ${journal.mood}`] : []),
        ...(journal.location ? [`Location: ${journal.location}`] : [])
      ]

      metadata.forEach(line => {
        pdf.text(line, 15, yPosition)
        yPosition += 6
      })

      yPosition += 5

      // Tags
      if (journal.tags && journal.tags.length > 0) {
        pdf.setFontSize(10)
        pdf.setTextColor(60, 179, 113)
        const tagsText = `Tags: ${journal.tags.map(tag => `#${tag}`).join(', ')}`
        const tagLines = pdf.splitTextToSize(tagsText, 180)
        pdf.text(tagLines, 15, yPosition)
        yPosition += (tagLines.length * 5) + 8
      }

      // Content
      pdf.setFontSize(11)
      pdf.setTextColor(40, 40, 40)

      const contentLines = pdf.splitTextToSize(journal.content, 180)
      const linesPerPage = Math.floor((pdf.internal.pageSize.height - yPosition - 20) / 5)

      let currentLine = 0

      while (currentLine < contentLines.length) {
        if (currentLine > 0) {
          pdf.addPage()
          currentPage++
          yPosition = 20
        }

        const endLine = Math.min(currentLine + linesPerPage, contentLines.length)
        const pageLines = contentLines.slice(currentLine, endLine)

        pdf.text(pageLines, 15, yPosition)
        currentLine = endLine
      }
    }

    // Add footer to all pages
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text(`Generated by VidoraFrameForge on ${new Date().toLocaleDateString()}`, 15, pdf.internal.pageSize.height - 10)
      pdf.text(`Page ${i} of ${pageCount}`, pdf.internal.pageSize.width - 30, pdf.internal.pageSize.height - 10)
    }

    const fileName = `journal_collection_${new Date().toISOString().split('T')[0]}.pdf`
    pdf.save(fileName)

  } catch (error) {
    console.error('Error generating PDF collection:', error)
    throw new Error('Failed to generate PDF collection')
  }
}

export const exportMultiplePhotosToPDF = async (photos: PhotoExportData[]): Promise<void> => {
  try {
    const pdf = new jsPDF()

    // Add title page
    pdf.setFontSize(24)
    pdf.setTextColor(40, 40, 40)
    pdf.text('Photo Collection', pdf.internal.pageSize.width / 2, 50, { align: 'center' })

    pdf.setFontSize(14)
    pdf.setTextColor(100, 100, 100)
    pdf.text(`Exported on ${new Date().toLocaleDateString()}`, pdf.internal.pageSize.width / 2, 70, { align: 'center' })
    pdf.text(`${photos.length} photo${photos.length !== 1 ? 's' : ''}`, pdf.internal.pageSize.width / 2, 85, { align: 'center' })

    let currentPage = 1

    // Add each photo
    for (const photo of photos) {
      pdf.addPage()
      currentPage++

      // Photo title
      pdf.setFontSize(18)
      pdf.setTextColor(40, 40, 40)
      const titleLines = pdf.splitTextToSize(photo.title, 180)
      pdf.text(titleLines, 15, 25)

      let yPosition = 35 + (titleLines.length * 7)

      // Metadata
      pdf.setFontSize(11)
      pdf.setTextColor(100, 100, 100)

      const metadata = [
        `Date: ${new Date(photo.createdAt).toLocaleDateString()}`,
        `File: ${photo.fileName}`,
        `Size: ${(photo.size / 1024 / 1024).toFixed(2)} MB`,
        ...(photo.album ? [`Album: ${photo.album}`] : [])
      ]

      metadata.forEach(line => {
        pdf.text(line, 15, yPosition)
        yPosition += 6
      })

      yPosition += 5

      // Tags
      if (photo.tags && photo.tags.length > 0) {
        pdf.setFontSize(10)
        pdf.setTextColor(59, 130, 246)
        const tagsText = `Tags: ${photo.tags.map(tag => `#${tag}`).join(', ')}`
        const tagLines = pdf.splitTextToSize(tagsText, 180)
        pdf.text(tagLines, 15, yPosition)
        yPosition += (tagLines.length * 5) + 8
      }

      // Description
      if (photo.description) {
        pdf.setFontSize(11)
        pdf.setTextColor(40, 40, 40)
        const descLines = pdf.splitTextToSize(photo.description, 180)
        pdf.text(descLines, 15, yPosition)
        yPosition += (descLines.length * 5) + 10
      }

      // URL
      pdf.setFontSize(9)
      pdf.setTextColor(150, 150, 150)
      pdf.text(`URL: ${photo.url}`, 15, yPosition)
    }

    // Add footer to all pages
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text(`Generated by VidoraFrameForge on ${new Date().toLocaleDateString()}`, 15, pdf.internal.pageSize.height - 10)
      pdf.text(`Page ${i} of ${pageCount}`, pdf.internal.pageSize.width - 30, pdf.internal.pageSize.height - 10)
    }

    const fileName = `photo_collection_${new Date().toISOString().split('T')[0]}.pdf`
    pdf.save(fileName)

  } catch (error) {
    console.error('Error generating photo PDF collection:', error)
    throw new Error('Failed to generate photo PDF collection')
  }
}

export const exportMultipleVideosToPDF = async (videos: VideoExportData[]): Promise<void> => {
  try {
    const pdf = new jsPDF()

    // Add title page
    pdf.setFontSize(24)
    pdf.setTextColor(40, 40, 40)
    pdf.text('Video Collection', pdf.internal.pageSize.width / 2, 50, { align: 'center' })

    pdf.setFontSize(14)
    pdf.setTextColor(100, 100, 100)
    pdf.text(`Exported on ${new Date().toLocaleDateString()}`, pdf.internal.pageSize.width / 2, 70, { align: 'center' })
    pdf.text(`${videos.length} video${videos.length !== 1 ? 's' : ''}`, pdf.internal.pageSize.width / 2, 85, { align: 'center' })

    let currentPage = 1

    // Add each video
    for (const video of videos) {
      pdf.addPage()
      currentPage++

      // Video title
      pdf.setFontSize(18)
      pdf.setTextColor(40, 40, 40)
      const titleLines = pdf.splitTextToSize(video.title, 180)
      pdf.text(titleLines, 15, 25)

      let yPosition = 35 + (titleLines.length * 7)

      // Metadata
      pdf.setFontSize(11)
      pdf.setTextColor(100, 100, 100)

      const metadata = [
        `Date: ${new Date(video.createdAt).toLocaleDateString()}`,
        `File: ${video.fileName}`,
        `Size: ${(video.size / 1024 / 1024).toFixed(2)} MB`,
        ...(video.duration ? [`Duration: ${Math.floor(video.duration / 60)}:${(video.duration % 60).toString().padStart(2, '0')}`] : []),
        ...(video.category ? [`Category: ${video.category}`] : [])
      ]

      metadata.forEach(line => {
        pdf.text(line, 15, yPosition)
        yPosition += 6
      })

      yPosition += 5

      // Tags
      if (video.tags && video.tags.length > 0) {
        pdf.setFontSize(10)
        pdf.setTextColor(147, 51, 234)
        const tagsText = `Tags: ${video.tags.map(tag => `#${tag}`).join(', ')}`
        const tagLines = pdf.splitTextToSize(tagsText, 180)
        pdf.text(tagLines, 15, yPosition)
        yPosition += (tagLines.length * 5) + 8
      }

      // Description
      if (video.description) {
        pdf.setFontSize(11)
        pdf.setTextColor(40, 40, 40)
        const descLines = pdf.splitTextToSize(video.description, 180)
        pdf.text(descLines, 15, yPosition)
        yPosition += (descLines.length * 5) + 10
      }

      // URL
      pdf.setFontSize(9)
      pdf.setTextColor(150, 150, 150)
      pdf.text(`URL: ${video.url}`, 15, yPosition)
    }

    // Add footer to all pages
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text(`Generated by VidoraFrameForge on ${new Date().toLocaleDateString()}`, 15, pdf.internal.pageSize.height - 10)
      pdf.text(`Page ${i} of ${pageCount}`, pdf.internal.pageSize.width - 30, pdf.internal.pageSize.height - 10)
    }

    const fileName = `video_collection_${new Date().toISOString().split('T')[0]}.pdf`
    pdf.save(fileName)

  } catch (error) {
    console.error('Error generating video PDF collection:', error)
    throw new Error('Failed to generate video PDF collection')
  }
}

// Timeline export interface
export interface TimelineItem {
  type: 'photo' | 'video' | 'journal'
  title: string
  description?: string
  content?: string
  createdAt: Date
  tags?: string[]
  mood?: string
  url?: string
  thumbnailUrl?: string
}

export interface TimelineExportData {
  userName: string
  items: TimelineItem[]
  dateRange: {
    start: Date
    end: Date
  }
}

// Export full timeline as PDF
export const exportTimelineToPDF = async (data: TimelineExportData): Promise<void> => {
  try {
    const pdf = new jsPDF()

    // Title page
    pdf.setFontSize(24)
    pdf.setTextColor(40, 40, 40)
    pdf.text('My Life Timeline', pdf.internal.pageSize.width / 2, 50, { align: 'center' })

    pdf.setFontSize(14)
    pdf.setTextColor(100, 100, 100)
    pdf.text(data.userName, pdf.internal.pageSize.width / 2, 70, { align: 'center' })

    pdf.setFontSize(11)
    pdf.setTextColor(120, 120, 120)
    const startDate = new Date(data.dateRange.start).toLocaleDateString()
    const endDate = new Date(data.dateRange.end).toLocaleDateString()
    pdf.text(`${startDate} - ${endDate}`, pdf.internal.pageSize.width / 2, 85, { align: 'center' })
    pdf.text(`${data.items.length} memories`, pdf.internal.pageSize.width / 2, 95, { align: 'center' })

    // Summary stats
    const photoCount = data.items.filter(i => i.type === 'photo').length
    const videoCount = data.items.filter(i => i.type === 'video').length
    const journalCount = data.items.filter(i => i.type === 'journal').length

    pdf.setFontSize(10)
    pdf.setTextColor(60, 60, 60)
    pdf.text(`📷 ${photoCount} photos  |  🎥 ${videoCount} videos  |  📝 ${journalCount} journals`, 
      pdf.internal.pageSize.width / 2, 110, { align: 'center' })

    // Timeline content
    pdf.addPage()
    let yPosition = 20

    // Group items by month
    const itemsByMonth: { [key: string]: TimelineItem[] } = {}
    data.items.forEach(item => {
      const monthKey = new Date(item.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long' })
      if (!itemsByMonth[monthKey]) {
        itemsByMonth[monthKey] = []
      }
      itemsByMonth[monthKey].push(item)
    })

    Object.entries(itemsByMonth).forEach(([month, items]) => {
      // Check if we need a new page
      if (yPosition > pdf.internal.pageSize.height - 40) {
        pdf.addPage()
        yPosition = 20
      }

      // Month header
      pdf.setFillColor(59, 130, 246)
      pdf.rect(10, yPosition - 5, pdf.internal.pageSize.width - 20, 10, 'F')
      pdf.setFontSize(12)
      pdf.setTextColor(255, 255, 255)
      pdf.text(month, 15, yPosition + 2)
      yPosition += 15

      // Items in this month
      items.forEach((item, index) => {
        if (yPosition > pdf.internal.pageSize.height - 50) {
          pdf.addPage()
          yPosition = 20
        }

        // Type icon and title
        pdf.setFontSize(11)
        pdf.setTextColor(40, 40, 40)
        const typeEmoji = item.type === 'photo' ? '📷' : item.type === 'video' ? '🎥' : '📝'
        pdf.text(`${typeEmoji} ${item.title}`, 20, yPosition)
        yPosition += 6

        // Date
        pdf.setFontSize(9)
        pdf.setTextColor(120, 120, 120)
        pdf.text(new Date(item.createdAt).toLocaleDateString('en-US', { 
          month: 'short', 
          day: 'numeric', 
          year: 'numeric',
          hour: '2-digit',
          minute: '2-digit'
        }), 20, yPosition)
        yPosition += 5

        // Mood (for journals)
        if (item.mood) {
          pdf.setFontSize(9)
          pdf.setTextColor(234, 179, 8)
          pdf.text(`Mood: ${item.mood}`, 20, yPosition)
          yPosition += 5
        }

        // Description or content
        if (item.description || item.content) {
          pdf.setFontSize(9)
          pdf.setTextColor(60, 60, 60)
          const text = item.description || item.content || ''
          const lines = pdf.splitTextToSize(text.substring(0, 300), 170)
          pdf.text(lines.slice(0, 3), 20, yPosition)
          yPosition += lines.slice(0, 3).length * 4 + 2
        }

        // Tags
        if (item.tags && item.tags.length > 0) {
          pdf.setFontSize(8)
          pdf.setTextColor(147, 51, 234)
          const tagsText = item.tags.slice(0, 5).map(tag => `#${tag}`).join(' ')
          pdf.text(tagsText, 20, yPosition)
          yPosition += 5
        }

        // URL (for reference)
        if (item.url) {
          pdf.setFontSize(7)
          pdf.setTextColor(180, 180, 180)
          pdf.text(item.url.substring(0, 80), 20, yPosition)
          yPosition += 5
        }

        yPosition += 8 // Space between items

        // Separator line
        pdf.setDrawColor(220, 220, 220)
        pdf.line(15, yPosition - 3, pdf.internal.pageSize.width - 15, yPosition - 3)
      })

      yPosition += 5
    })

    // Add footer to all pages
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text(`Generated by VidoraFrameForge on ${new Date().toLocaleDateString()}`, 15, pdf.internal.pageSize.height - 10)
      pdf.text(`Page ${i} of ${pageCount}`, pdf.internal.pageSize.width - 30, pdf.internal.pageSize.height - 10)
    }

    const fileName = `timeline_${data.userName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${new Date().toISOString().split('T')[0]}.pdf`
    pdf.save(fileName)

  } catch (error) {
    console.error('Error generating timeline PDF:', error)
    throw new Error('Failed to generate timeline PDF')
  }
}

// ZIP export interface
export interface ZipExportData {
  userName: string
  photos: Array<{
    title: string
    url: string
    fileName: string
    description?: string
    tags?: string[]
    createdAt: Date
  }>
  journals: Array<{
    title: string
    content: string
    mood?: string
    tags?: string[]
    createdAt: Date
  }>
}

// Export as ZIP with images and journals
export const exportAsZip = async (data: ZipExportData): Promise<void> => {
  try {
    // Dynamic import of JSZip
    const JSZip = (await import('jszip')).default
    const zip = new JSZip()

    // Create folders
    const photosFolder = zip.folder('photos')
    const journalsFolder = zip.folder('journals')

    // Add README
    const readmeContent = `VidoraFrameForge Export
    
User: ${data.userName}
Export Date: ${new Date().toLocaleDateString()}
Total Photos: ${data.photos.length}
Total Journals: ${data.journals.length}

---

This archive contains:
- photos/ - All your photo files
- journals/ - All your journal entries in text format
- index.json - Metadata for all your content

Enjoy your memories!
`
    zip.file('README.txt', readmeContent)

    // Create index metadata
    const indexData = {
      user: data.userName,
      exportDate: new Date().toISOString(),
      totalPhotos: data.photos.length,
      totalJournals: data.journals.length,
      photos: data.photos.map(p => ({
        title: p.title,
        fileName: p.fileName,
        description: p.description,
        tags: p.tags,
        createdAt: p.createdAt
      })),
      journals: data.journals.map(j => ({
        title: j.title,
        mood: j.mood,
        tags: j.tags,
        createdAt: j.createdAt
      }))
    }
    zip.file('index.json', JSON.stringify(indexData, null, 2))

    // Download and add photos
    for (let i = 0; i < data.photos.length; i++) {
      const photo = data.photos[i]
      try {
        const response = await fetch(photo.url)
        const blob = await response.blob()
        const fileName = `${i + 1}_${photo.fileName}`.replace(/[^a-z0-9._-]/gi, '_')
        
        if (photosFolder) {
          photosFolder.file(fileName, blob)
          
          // Add metadata file for each photo
          const metadata = `Title: ${photo.title}
Date: ${new Date(photo.createdAt).toLocaleString()}
${photo.description ? `Description: ${photo.description}\n` : ''}${photo.tags && photo.tags.length > 0 ? `Tags: ${photo.tags.join(', ')}\n` : ''}`
          
          photosFolder.file(`${i + 1}_${photo.title.replace(/[^a-z0-9]/gi, '_')}.txt`, metadata)
        }
      } catch (error) {
        console.error(`Failed to download photo: ${photo.title}`, error)
        // Continue with other photos
      }
    }

    // Add journals as text files
    data.journals.forEach((journal, index) => {
      const fileName = `${index + 1}_${journal.title.replace(/[^a-z0-9]/gi, '_')}.txt`
      const content = `${journal.title}
${new Date(journal.createdAt).toLocaleString()}
${journal.mood ? `Mood: ${journal.mood}\n` : ''}${journal.tags && journal.tags.length > 0 ? `Tags: ${journal.tags.join(', ')}\n` : ''}
---

${journal.content}
`
      if (journalsFolder) {
        journalsFolder.file(fileName, content)
      }
    })

    // Generate ZIP and trigger download
    const zipBlob = await zip.generateAsync({ type: 'blob' })
    const url = URL.createObjectURL(zipBlob)
    const link = document.createElement('a')
    link.href = url
    link.download = `vidoraframeforge_${data.userName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${new Date().toISOString().split('T')[0]}.zip`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)

  } catch (error) {
    console.error('Error generating ZIP export:', error)
    throw new Error('Failed to generate ZIP export')
  }
}